on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: |
          nix flake check \
            --show-trace \
            --print-build-logs
